#!/usr/bin/env python3
"""Migrate Engram v1 SQLite data into the Engram v2 Postgres schema.

Usage:
    scripts/migrate_sqlite_to_postgres.py --sqlite instance/engram.db --database-url "$DATABASE_URL"

The script loads the canonical v2 schema first, inserts entities/tags/links, and
validates source-to-target row counts before committing. It intentionally avoids
AI/vector tables; embeddings are regenerated by later v2 jobs.
"""

from __future__ import annotations

import argparse
import json
import os
import sqlite3
import sys
import uuid
from datetime import datetime
from pathlib import Path
from typing import Any

import psycopg2
from psycopg2.extras import Json, execute_values

ROOT = Path(__file__).resolve().parents[1]
ENTITY_TABLES = ("notes", "projects", "tasks", "areas", "resources", "people")
OPTIONAL_TABLES = ("tags", "note_tags", "resource_tags", "note_projects", "links")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--sqlite", default=str(ROOT / "instance" / "engram.db"), help="source SQLite DB")
    parser.add_argument("--database-url", default=os.environ.get("DATABASE_URL"), help="target Postgres URL")
    parser.add_argument("--schema", default=str(ROOT / "docs" / "SCHEMA.sql"), help="schema SQL file")
    return parser.parse_args()


def rows(conn: sqlite3.Connection, table: str) -> list[sqlite3.Row]:
    try:
        return list(conn.execute(f"SELECT * FROM {table}"))
    except sqlite3.OperationalError:
        return []


def valid_uuid(value: Any) -> bool:
    if not value:
        return False
    try:
        uuid.UUID(str(value))
        return True
    except (TypeError, ValueError):
        return False


def table_count(conn: sqlite3.Connection, table: str) -> int:
    try:
        return int(conn.execute(f"SELECT COUNT(*) FROM {table}").fetchone()[0])
    except sqlite3.OperationalError:
        return 0


def iso(value: Any) -> Any:
    if not value:
        return None
    if isinstance(value, str):
        return value
    if isinstance(value, datetime):
        return value.isoformat()
    return value


def json_load(value: Any, default: Any) -> Any:
    if value in (None, ""):
        return default
    if isinstance(value, (dict, list)):
        return value
    try:
        return json.loads(value)
    except Exception:
        return default


def entity_payload(table: str, row: sqlite3.Row) -> tuple[str, str, str | None, str | None, str, str, Any, Any, str | None, str | None, Any, Any]:
    data = dict(row)
    entity_type = table[:-1] if table.endswith("s") else table
    title = None
    content = None
    status = "active"
    lifecycle = "active"
    follow_up_at = None
    source = "migration:v1"
    reference_url = None
    properties: dict[str, Any] = {"legacy_table": table}
    ai_meta: dict[str, Any] = {}

    if table == "notes":
        entity_type = "note"
        content = data.get("raw_text")
        title = (content or "").splitlines()[0][:200] if content else None
        lifecycle = "archived" if data.get("is_archived") else "active"
        properties.update({"bucket": data.get("bucket"), "note_type": data.get("note_type")})
        ai_meta = json_load(data.get("ai_meta"), {})
    elif table == "projects":
        entity_type = "project"
        title = data.get("name")
        content = data.get("description")
        follow_up_at = iso(data.get("deadline"))
        lifecycle = "archived" if data.get("is_archived") else "active"
        properties.update({"priority": data.get("priority"), "color": data.get("color")})
    elif table == "tasks":
        entity_type = "task"
        title = data.get("title")
        content = data.get("description")
        status = (data.get("status") or "pending").lower()
        follow_up_at = iso(data.get("due_date"))
        properties.update({"priority": data.get("priority"), "inline_title_hash": data.get("inline_title_hash")})
    elif table == "areas":
        entity_type = "area"
        title = data.get("name")
        content = data.get("description")
        properties.update({"color": data.get("color")})
    elif table == "resources":
        entity_type = "resource"
        title = data.get("title")
        content = "\n\n".join(x for x in [data.get("description"), data.get("my_notes")] if x)
        reference_url = data.get("url")
        properties.update({
            "resource_type": data.get("resource_type"),
            "is_read": bool(data.get("is_read")) if data.get("is_read") is not None else None,
            "rating": data.get("rating"),
            "author": data.get("author"),
            "published_at": iso(data.get("published_at")),
        })
    elif table == "people":
        entity_type = "person"
        title = data.get("name")
        content = data.get("notes_text")
        properties.update({
            "email": data.get("email"),
            "external_ids": json_load(data.get("external_ids"), {}),
            "last_contacted_at": iso(data.get("last_contacted_at")),
        })

    return (
        data["id"], entity_type, title, content, status, lifecycle,
        follow_up_at, source, reference_url, Json({k: v for k, v in properties.items() if v is not None}),
        Json(ai_meta), iso(data.get("created_at")), iso(data.get("modified_at")),
    )


def migrate(sqlite_path: Path, database_url: str, schema_path: Path) -> dict[str, int]:
    if not sqlite_path.exists():
        raise FileNotFoundError(f"SQLite DB not found: {sqlite_path}")
    if not database_url:
        raise ValueError("DATABASE_URL / --database-url is required")

    src = sqlite3.connect(sqlite_path)
    src.row_factory = sqlite3.Row
    pg = psycopg2.connect(database_url)
    pg.autocommit = False
    try:
        with pg.cursor() as cur:
            cur.execute(schema_path.read_text())
            for table in ("entity_tags", "entity_links", "entity_events", "entity_chunks", "jobs", "entities", "tags"):
                cur.execute(f"DELETE FROM {table}")

            tag_rows = rows(src, "tags")
            if tag_rows:
                execute_values(cur, """
                    INSERT INTO tags (id, name, color, created_at, updated_at)
                    VALUES %s ON CONFLICT (id) DO NOTHING
                """, [(r["id"], r["name"], r["color"], iso(r["created_at"]), iso(r["modified_at"])) for r in tag_rows])

            entity_values = []
            for table in ENTITY_TABLES:
                entity_values.extend(entity_payload(table, r) for r in rows(src, table))
            if entity_values:
                execute_values(cur, """
                    INSERT INTO entities
                      (id, type, title, content, status, lifecycle, follow_up_at, source,
                       reference_url, properties, ai_meta, created_at, updated_at)
                    VALUES %s ON CONFLICT (id) DO NOTHING
                """, entity_values)

            entity_ids = {value[0] for value in entity_values}
            tag_ids = {r["id"] for r in tag_rows}

            tag_values = [(r["note_id"], r["tag_id"]) for r in rows(src, "note_tags") if r["note_id"] in entity_ids and r["tag_id"] in tag_ids]
            tag_values += [(r["resource_id"], r["tag_id"]) for r in rows(src, "resource_tags") if r["resource_id"] in entity_ids and r["tag_id"] in tag_ids]
            if tag_values:
                execute_values(cur, "INSERT INTO entity_tags (entity_id, tag_id) VALUES %s ON CONFLICT DO NOTHING", tag_values)

            link_values = []
            for r in rows(src, "tasks"):
                for field, link_type in (("project_id", "parent"), ("area_id", "parent"), ("note_id", "derived_from")):
                    if valid_uuid(r[field]):
                        link_values.append((r["id"], r[field], link_type, 1.0, "migration:v1"))
            for r in rows(src, "notes"):
                for field, link_type in (("project_id", "related"), ("area_id", "related"), ("person_id", "mentions")):
                    if valid_uuid(r[field]):
                        link_values.append((r["id"], r[field], link_type, 1.0, "migration:v1"))
            link_values += [
                (r["note_id"], r["project_id"], "related", 1.0, "migration:v1")
                for r in rows(src, "note_projects")
                if valid_uuid(r["note_id"]) and valid_uuid(r["project_id"])
            ]
            for r in rows(src, "projects"):
                if valid_uuid(r["area_id"]):
                    link_values.append((r["id"], r["area_id"], "parent", 1.0, "migration:v1"))
            for r in rows(src, "resources"):
                if valid_uuid(r["area_id"]):
                    link_values.append((r["id"], r["area_id"], "related", 1.0, "migration:v1"))
            link_values += [
                (r["src_id"], r["dst_id"], r["link_type"], r["weight"] or 1.0, r["source"] or "migration:v1")
                for r in rows(src, "links")
                if valid_uuid(r["src_id"]) and valid_uuid(r["dst_id"])
            ]
            link_values = [link for link in link_values if link[0] in entity_ids and link[1] in entity_ids]
            if link_values:
                execute_values(cur, """
                    INSERT INTO entity_links (src_id, dst_id, link_type, weight, source)
                    VALUES %s ON CONFLICT (src_id, dst_id, link_type) DO NOTHING
                """, link_values)

            expected_entities = sum(table_count(src, t) for t in ENTITY_TABLES)
            expected_tags = table_count(src, "tags")
            cur.execute("SELECT COUNT(*) FROM entities")
            actual_entities = cur.fetchone()[0]
            cur.execute("SELECT COUNT(*) FROM tags")
            actual_tags = cur.fetchone()[0]
            if actual_entities != expected_entities:
                raise RuntimeError(f"entity count mismatch: expected {expected_entities}, got {actual_entities}")
            if actual_tags != expected_tags:
                raise RuntimeError(f"tag count mismatch: expected {expected_tags}, got {actual_tags}")
            pg.commit()
            return {"entities": actual_entities, "tags": actual_tags, "links": len(link_values)}
    except Exception:
        pg.rollback()
        raise
    finally:
        pg.close()
        src.close()


def main() -> int:
    args = parse_args()
    try:
        counts = migrate(Path(args.sqlite), args.database_url, Path(args.schema))
    except Exception as exc:
        print(f"migration failed: {exc}", file=sys.stderr)
        return 1
    print("migration complete")
    print(json.dumps(counts, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
